version: '3'
services:
        web:
            image: nodejs-app
            build: .
            command: "node server.js"
            ports: 
                - "9001:7000"
            depends_on: 
                - "mongo"
        mongo:
            image: "mongo"
            ports: 
                - "27017:27017"